In [ ]:
import cv2
import os
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as lda

In [ ]:
from google.colab import drive
drive.mount('/content/drive') 

Mounted at /content/drive


In [ ]:
images = '/content/drive/My Drive/Colab Notebooks/Animals_Folder'
images

'/content/drive/My Drive/Colab Notebooks/Animals_Folder'

In [ ]:
def load_image(images):
  img = []
  for i in os.listdir(images):
    img1 = cv2.imread(os.path.join(images,i))
    img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
    img1 = cv2.resize(img1, (128,128))
    img.append(img1)
  return img

In [ ]:
Animals = load_image(images)
Animals[9].shape

(128, 128)

In [ ]:
def get_array(images):
  array = np.array(Animals)
  array = np.reshape(array, (array.shape[0], array.shape[1] * array.shape[2]))
  return array

In [ ]:
X = get_array(images)
X.shape

(40, 16384)

In [ ]:
y1 = np.zeros(20, dtype=bool)
y2 = np.ones(20, dtype=bool)
Y = np.concatenate((y1,y2), axis=0)
Y.shape

(40,)

In [ ]:
svm1 = SVC()
svm1.fit(X,Y)

SVC()

In [ ]:
print(svm1.support_vectors_)

[[ 83.  84.  84. ...  27.  23.  94.]
 [ 54.  43.  36. ...   2.   3.   2.]
 [104. 101.  94. ... 173. 171. 167.]
 ...
 [ 68.  66.  66. ...  77.  59.  75.]
 [ 52.  51.  74. ...  55.  56.  44.]
 [230. 207. 225. ... 139.  78. 129.]]


In [ ]:
p = svm1.predict(X)
p

array([False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
cm = confusion_matrix(p,Y)
cm

array([[19,  0],
       [ 1, 20]])

In [ ]:
accuracy_score(p,Y)

0.975

In [ ]:
LDA = lda()
LDA.fit(X,Y)

LinearDiscriminantAnalysis()

In [ ]:
LDA.transform(X)

array([[-1.37256348],
       [-1.66459295],
       [-1.55512063],
       [-1.09063188],
       [-1.50191123],
       [-1.1523138 ],
       [-1.40886893],
       [-1.867274  ],
       [-1.87382734],
       [-1.56313486],
       [-1.93365977],
       [-0.26334596],
       [-1.54570669],
       [-2.02917525],
       [-1.08001237],
       [-1.14048004],
       [-1.09222977],
       [-1.56125858],
       [-1.12382667],
       [-1.04577138],
       [ 1.81296896],
       [ 1.49505346],
       [ 1.68602574],
       [ 2.02247764],
       [ 1.18750769],
       [ 1.80268619],
       [ 1.74089844],
       [ 1.52380092],
       [-4.22798837],
       [ 1.53270397],
       [ 1.71199064],
       [ 2.11695437],
       [ 1.80268619],
       [ 2.00002133],
       [ 1.72433319],
       [ 1.88693553],
       [ 1.61188811],
       [ 0.92533838],
       [ 1.52380092],
       [ 1.98562228]])

In [ ]:
p = LDA.predict(X)
p

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
cm2 = confusion_matrix(p,Y)
cm2

array([[20,  1],
       [ 0, 19]])

In [ ]:
accuracy_score(p,Y)

0.975

In [ ]:
pca = PCA()
pca.fit(X)
print(pca.explained_variance_ratio_)

[1.51318354e-01 8.66473770e-02 6.79937916e-02 5.83725052e-02
 4.38806273e-02 4.10989889e-02 3.98984748e-02 3.49061737e-02
 3.15495984e-02 2.91865506e-02 2.81213734e-02 2.60922558e-02
 2.38299340e-02 2.29824675e-02 2.27742071e-02 2.17580737e-02
 2.02809969e-02 1.96545354e-02 1.80575110e-02 1.77605544e-02
 1.73330725e-02 1.65028570e-02 1.63646742e-02 1.52165975e-02
 1.42447354e-02 1.38888873e-02 1.31928228e-02 1.27301630e-02
 1.24881204e-02 1.21090544e-02 1.16433776e-02 1.04042517e-02
 9.71283915e-03 8.60169732e-03 6.73107248e-03 2.30288027e-03
 3.68545955e-04 2.06777973e-31 9.01610635e-32 2.86892961e-32]


In [ ]:
X1 = pca.fit_transform(X)
X1.shape

(40, 40)

In [ ]:
SVM1 = SVC(kernel='linear')
SVM1.fit(X1,Y)

SVC(kernel='linear')

In [ ]:
p2 = SVM1.predict(X1)
p2

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [ ]:
cm = confusion_matrix(p2,Y)
cm

array([[20,  0],
       [ 0, 20]])

In [ ]:
accuracy_score(p2,Y)

1.0